
# cp /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA/TESTS_2017_FGM/fgm/C2_CQ_FGM_CAVF__20130602_192530_20130605_014110_V01.cef.gz  /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA
# cp /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA/TESTS_2017_FGM/header_includes/fgm/C2_CH_FGM_CAVF.ceh  /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA
cp /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA/TESTS_2017_FGM/header_includes/CL_CH_MISSION.ceh  /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA
cp /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA/TESTS_2017_FGM/header_includes/C2_CH_OBS.ceh  /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA
cp /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA/TESTS_2017_FGM/header_includes/fgm/CL_CH_FGM_EXP.ceh  /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA
cp /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA/TESTS_2017_FGM/header_includes/fgm/C2_CH_FGM_INST.ceh  /home/spw/C/CAA-DEV-APPS-SAMPLE-DATA
